server:
  port: 8080

kafka:
  bootstrap-servers: localhost:9092

integracao:
  url: https://user-info.herokuapp.com/users

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: basic

rabbit:
  spring:
    rabbitmq:
      hots: localhost
      port: 5672
      username: guest
      password: guest
      queue: sessaoecnerrada


